using System.Collections.Generic;
using System.Linq;

namespace FuncSharp.Tests.Generative;

/// <summary>
/// Shrinkers are used for lowering the value generated by generators. So that if a test fails, the test framework will try reducing the value to find the lowest failing value.
/// </summary>
internal class OptionShrinkers
{
    internal IEnumerable<IOption<short>> Short(IOption<short> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued((short)(option.GetOrDefault() - 1));
    }

    internal IEnumerable<IOption<List<short>>> ShortList(IOption<List<short>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<short>>();
            yield return option.Map(l => l.Select(i => (short)(i - 1)).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }

    internal IEnumerable<IOption<short?>> NullableShort(IOption<short?> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Valued((short?)(option.GetOrDefault() - 1));
            yield return Option.Valued((short?)null);
            yield return Option.Empty<short?>();
        }
    }

    internal IEnumerable<IOption<int>> Int(IOption<int> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued(option.GetOrDefault() - 1);
    }

    internal IEnumerable<IOption<List<int>>> IntList(IOption<List<int>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<int>>();
            yield return option.Map(l => l.Select(i => i - 1).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }

    internal IEnumerable<IOption<int?>> NullableInt(IOption<int?> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Valued(option.GetOrDefault() - 1);
            yield return Option.Valued((int?)null);
            yield return Option.Empty<int?>();
        }
    }

    internal IEnumerable<IOption<long>> Long(IOption<long> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued(option.GetOrDefault() - 1);
    }

    internal IEnumerable<IOption<List<long>>> LongList(IOption<List<long>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<long>>();
            yield return option.Map(l => l.Select(i => i - 1).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }

    internal IEnumerable<IOption<long?>> NullableLong(IOption<long?> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Valued(option.GetOrDefault() - 1);
            yield return Option.Valued((long?)null);
            yield return Option.Empty<long?>();
        }
    }

    internal IEnumerable<IOption<decimal>> Decimal(IOption<decimal> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued(option.GetOrDefault() - 0.1m);
    }

    internal IEnumerable<IOption<List<decimal>>> DecimalList(IOption<List<decimal>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<decimal>>();
            yield return option.Map(l => l.Select(i => i - 1).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }

    internal IEnumerable<IOption<decimal?>> NullableDecimal(IOption<decimal?> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Valued(option.GetOrDefault() - 0.1m);
            yield return Option.Valued((decimal?)null);
            yield return Option.Empty<decimal?>();
        }
    }

    internal IEnumerable<IOption<double>> Double(IOption<double> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued(option.GetOrDefault() - 0.1d);
    }

    internal IEnumerable<IOption<List<double>>> DoubleList(IOption<List<double>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<double>>();
            yield return option.Map(l => l.Select(i => i - 1).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }

    internal IEnumerable<IOption<double?>> NullableDouble(IOption<double?> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Valued(option.GetOrDefault() - 0.1d);
            yield return Option.Valued((double?)null);
            yield return Option.Empty<double?>();
        }
    }

    internal IEnumerable<IOption<ReferenceType>> ReferenceType(IOption<ReferenceType> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued(new ReferenceType(option.GetOrDefault().Value - 1));
    }

    internal IEnumerable<IOption<List<ReferenceType>>> ReferenceTypeList(IOption<List<ReferenceType>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<ReferenceType>>();
            yield return option.Map(l => l.Select(t => new ReferenceType(t.Value - 1)).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }

    internal IEnumerable<IOption<ReferenceTypeBase>> ReferenceTypeBase(IOption<ReferenceTypeBase> option)
    {
        if(option.NonEmpty)
            yield return Option.Valued(new ReferenceTypeBase(option.GetOrDefault().BaseValue - 1));
    }

    internal IEnumerable<IOption<List<ReferenceTypeBase>>> ReferenceTypeBaseList(IOption<List<ReferenceTypeBase>> option)
    {
        if(option.NonEmpty)
        {
            yield return Option.Empty<List<ReferenceTypeBase>>();
            yield return option.Map(l => l.Select(t => new ReferenceTypeBase(t.BaseValue - 1)).ToList());
            yield return option.Map(l => l.Skip(1).ToList());
            yield return option.Map(l => l.SkipLast(1).ToList());
        }
    }
}
