using System.Collections.Generic;

namespace FuncSharp.Tests.Generative;

/// <summary>
/// Shrinkers are used for lowering the value generated by generators. So that if a test fails, the test framework will try reducing the value to find the lowest failing value.
/// </summary>
internal static class Shrinkers
{
    public static OptionShrinkers Options { get; } = new OptionShrinkers();
}
